# Generated by Django 2.1.7 on 2019-06-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FNI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='식품명')),
                ('food_group', models.CharField(blank=True, max_length=20, null=True, verbose_name='식품군')),
                ('food_amount', models.FloatField(blank=True, default=0, null=True, verbose_name='1회 제공량(g)')),
                ('calorie', models.FloatField(blank=True, default=0, null=True, verbose_name='열량(kcal)')),
                ('carbs', models.FloatField(blank=True, default=0, null=True, verbose_name='탄수화물(g)')),
                ('protein', models.FloatField(blank=True, default=0, null=True, verbose_name='단백질(g)')),
                ('fat', models.FloatField(blank=True, default=0, null=True, verbose_name='지방(g)')),
                ('sugar', models.FloatField(blank=True, default=0, null=True, verbose_name='당류(g)')),
                ('salt', models.FloatField(blank=True, default=0, null=True, verbose_name='나트륨(mg')),
                ('cholesterol', models.FloatField(blank=True, default=0, null=True, verbose_name='콜레스테롤(mg)')),
                ('saturated_fatty_acid', models.FloatField(blank=True, default=0, null=True, verbose_name='포화지방산(g)')),
                ('trans_fat', models.FloatField(blank=True, default=0, null=True, verbose_name='트랜스지방(g)')),
            ],
            options={
                'verbose_name': '식품영양성분 DB',
                'verbose_name_plural': '식품영양성분 DB 목록',
            },
        ),
    ]
