# Generated by Django 2.1.7 on 2019-06-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fni',
            name='calorie',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='열량(kcal)'),
        ),
        migrations.AlterField(
            model_name='fni',
            name='carbs',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='탄수화물(g)'),
        ),
        migrations.AlterField(
            model_name='fni',
            name='cholesterol',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='콜레스테롤(mg)'),
        ),
        migrations.AlterField(
            model_name='fni',
            name='fat',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='지방(g)'),
        ),
        migrations.AlterField(
            model_name='fni',
            name='food_amount',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='1회 제공량(g)'),
        ),
        migrations.AlterField(
            model_name='fni',
            name='protein',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='단백질(g)'),
        ),
        migrations.AlterField(
            model_name='fni',
            name='salt',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='나트륨(mg'),
        ),
        migrations.AlterField(
            model_name='fni',
            name='saturated_fatty_acid',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='포화지방산(g)'),
        ),
        migrations.AlterField(
            model_name='fni',
            name='sugar',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='당류(g)'),
        ),
        migrations.AlterField(
            model_name='fni',
            name='trans_fat',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='트랜스지방(g)'),
        ),
    ]
