# Generated by Django 2.1.7 on 2019-06-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_auto_20190606_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fni',
            name='food_group',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='식품군'),
        ),
        migrations.AlterField(
            model_name='fni',
            name='food_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='식품명'),
        ),
    ]
