# Generated by Django 2.1.7 on 2019-06-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_auto_20190606_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='HFI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(blank=True, max_length=24, null=True, verbose_name='원료명')),
                ('material_number', models.CharField(blank=True, max_length=24, null=True, verbose_name='원료 인정번호')),
                ('daily_limit', models.CharField(blank=True, max_length=8, null=True, verbose_name='1일 섭취량 상한선')),
                ('feature', models.TextField(blank=True, null=True, verbose_name='주요 기능성')),
                ('caution', models.TextField(blank=True, null=True, verbose_name='섭취 주의사항')),
            ],
            options={
                'verbose_name': '건강기능식품 개별인정형 정보',
                'verbose_name_plural': '건강기능식품 개별인정형 정보 목록',
            },
        ),
        migrations.AlterModelOptions(
            name='fni',
            options={'verbose_name': '식품영양성분', 'verbose_name_plural': '식품영양성분 목록'},
        ),
    ]
