# Generated by Django 2.1.7 on 2019-06-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0007_auto_20190613_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hfi',
            name='daily_limit',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='1일 섭취량 상한선'),
        ),
    ]
