# Generated by Django 2.1.7 on 2019-06-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0008_auto_20190613_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hfi',
            name='daily_limit',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='1일 섭취량 상한선'),
        ),
        migrations.AlterField(
            model_name='hfi',
            name='material_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='원료명'),
        ),
        migrations.AlterField(
            model_name='hfi',
            name='material_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='원료 인정번호'),
        ),
    ]
