# Generated by Django 2.1.7 on 2019-06-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0009_auto_20190613_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hfi',
            name='material_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='원료명'),
        ),
    ]
