# Generated by Django 2.1.7 on 2019-06-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0010_auto_20190613_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='HFA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='원료명')),
                ('material_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='원료 인정번호')),
                ('raw_daily_limit', models.CharField(blank=True, max_length=20, null=True, verbose_name='1일 섭취량 상한선')),
                ('limit_standard', models.CharField(blank=True, max_length=5, null=True, verbose_name='섭취량 단위')),
                ('feature', models.TextField(blank=True, null=True, verbose_name='주요 기능성')),
                ('caution', models.TextField(blank=True, null=True, verbose_name='섭취 주의사항')),
            ],
            options={
                'verbose_name': '건강기능식품 기능성원료 인정현황',
                'verbose_name_plural': '건강기능식품 기능성원료 인정현황 목록',
            },
        ),
    ]
