# Generated by Django 2.1.7 on 2019-06-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0012_auto_20190614_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hfc',
            name='limit_standard',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='섭취량 단위'),
        ),
    ]
