# Generated by Django 2.1.7 on 2019-06-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0014_hfa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hfa',
            name='daily_intake',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1일 권 섭취량'),
        ),
        migrations.AlterField(
            model_name='hfa',
            name='material_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='원료명'),
        ),
    ]
