# Generated by Django 2.1.7 on 2019-06-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0015_auto_20190614_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hfa',
            name='daily_intake',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='1일 권 섭취량'),
        ),
    ]
