# Generated by Django 2.1.7 on 2019-05-25 07:05

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_composition', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=20, null=True), blank=True, null=True, size=8, unique=True, verbose_name='식단 구성')),
                ('recipe', models.TextField(blank=True, default='레시피', null=True, verbose_name='레시피')),
                ('date', models.DateField(blank=True, db_index=True, null=True, verbose_name='날짜')),
                ('time', models.CharField(blank=True, choices=[('아침', 'Breakfast'), ('점심', 'Launch'), ('저녁', 'Dinner'), ('간식(오전)', 'Snack(AM)'), ('간식(오후)', 'Snack(PM)')], default='아침', max_length=8, null=True, verbose_name='섭취 시간')),
            ],
            options={
                'verbose_name': '식단',
                'verbose_name_plural': '식단 목록',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TableLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_index=True, null=True, verbose_name='섭취 일자')),
                ('time', models.CharField(blank=True, choices=[('아침', 'Breakfast'), ('점심', 'Launch'), ('저녁', 'Dinner'), ('간식(오전)', 'Snack(AM)'), ('간식(오후)', 'Snack(PM)')], default='아침', max_length=8, null=True, verbose_name='섭취 시간')),
            ],
            options={
                'verbose_name': '섭취 기록',
                'verbose_name_plural': '섭취 기록 목록',
            },
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tables.Table')),
                ('calorie', models.FloatField(blank=True, default=0, null=True)),
                ('carbs', models.FloatField(blank=True, default=0, null=True)),
                ('fiber', models.FloatField(blank=True, default=0, null=True)),
                ('A_protein', models.FloatField(blank=True, default=0, null=True)),
                ('V_protein', models.FloatField(blank=True, default=0, null=True)),
                ('A_fat', models.FloatField(blank=True, default=0, null=True)),
                ('V_fat', models.FloatField(blank=True, default=0, null=True)),
                ('cholesterol', models.FloatField(blank=True, default=0, null=True)),
                ('salt', models.FloatField(blank=True, default=0, null=True)),
                ('potassium', models.FloatField(blank=True, default=0, null=True)),
                ('phosphorus', models.FloatField(blank=True, default=0, null=True)),
                ('A_calcium', models.FloatField(blank=True, default=0, null=True)),
                ('V_calcium', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': '영양정보',
                'verbose_name_plural': '영양정보 목록',
            },
        ),
        migrations.AddField(
            model_name='tablelog',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.Table', verbose_name='섭취 식단'),
        ),
        migrations.AddField(
            model_name='tablelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
        migrations.AlterUniqueTogether(
            name='tablelog',
            unique_together={('date', 'time')},
        ),
    ]
