# Generated by Django 2.2.5 on 2020-01-15 09:12

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_composition', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=20, null=True), blank=True, null=True, size=8, verbose_name='식단 구성')),
                ('ingredients', models.TextField(blank=True, default=' ', null=True, verbose_name='재료')),
                ('recipe', models.TextField(blank=True, default=' ', null=True, verbose_name='레시피')),
                ('tips', models.TextField(blank=True, default=' ', null=True, verbose_name='레시피 팁')),
                ('date', models.DateField(blank=True, db_index=True, null=True, verbose_name='날짜')),
                ('time', models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], default='Breakfast', max_length=16, null=True, verbose_name='섭취 시간')),
            ],
            options={
                'verbose_name': '식단',
                'verbose_name_plural': '식단 목록',
                'ordering': ['date', 'pk'],
                'unique_together': {('date', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tables.Table', verbose_name='식단')),
                ('calorie', models.FloatField(blank=True, default=0, null=True, verbose_name='칼로리')),
                ('carbs', models.FloatField(blank=True, default=0, null=True, verbose_name='탄수화물')),
                ('fiber', models.FloatField(blank=True, default=0, null=True, verbose_name='섬유질')),
                ('V_protein', models.FloatField(blank=True, default=0, null=True, verbose_name='식물성 단백질')),
                ('A_protein', models.FloatField(blank=True, default=0, null=True, verbose_name='동물성 단백질')),
                ('V_fat', models.FloatField(blank=True, default=0, null=True, verbose_name='식물성 지방')),
                ('A_fat', models.FloatField(blank=True, default=0, null=True, verbose_name='동물성 지방')),
                ('cholesterol', models.FloatField(blank=True, default=0, null=True, verbose_name='콜레스테롤')),
                ('salt', models.FloatField(blank=True, default=0, null=True, verbose_name='나트륨')),
                ('potassium', models.FloatField(blank=True, default=0, null=True, verbose_name='칼륨')),
                ('phosphorus', models.FloatField(blank=True, default=0, null=True, verbose_name='인')),
                ('V_calcium', models.FloatField(blank=True, default=0, null=True, verbose_name='식물성 칼슘')),
                ('A_calcium', models.FloatField(blank=True, default=0, null=True, verbose_name='동물성 칼슘')),
                ('V_iron', models.FloatField(blank=True, default=0, null=True, verbose_name='식물성 철')),
                ('A_iron', models.FloatField(blank=True, default=0, null=True, verbose_name='동물성 철')),
            ],
            options={
                'verbose_name': '영양정보',
                'verbose_name_plural': '영양정보 목록',
            },
        ),
        migrations.CreateModel(
            name='TableLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_index=True, default=django.utils.timezone.now, null=True, verbose_name='섭취 일자')),
                ('time', models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], default='Breakfast', max_length=16, null=True, verbose_name='섭취 시간')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.Table', verbose_name='섭취 식단')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '섭취 기록',
                'verbose_name_plural': '섭취 기록 목록',
                'ordering': ['date', 'pk'],
                'unique_together': {('user', 'date', 'time')},
            },
        ),
    ]
