# Generated by Django 2.1.7 on 2019-05-27 08:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='dietary_composition',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=20, null=True), blank=True, null=True, size=8, verbose_name='식단 구성'),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('date', 'time')},
        ),
    ]
