# Generated by Django 2.1.7 on 2019-05-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todaytable',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='날짜'),
        ),
    ]
