# Generated by Django 2.2.2 on 2019-06-27 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Defaults to filename, if left blank', max_length=255, null=True)),
                ('file', models.FileField(upload_to='.media/2019-06')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='A_calcium',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='동물성 칼슘'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='A_fat',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='동물성 지방'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='A_protein',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='동물성 단백질'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='V_calcium',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='식물성 칼슘'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='V_fat',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='식물성 지방'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='V_protein',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='식물성 단백질'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='calorie',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='칼로리'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='carbs',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='탄수화물'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='cholesterol',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='콜레스테롤'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='fiber',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='섬유질'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='phosphorus',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='인'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='potassium',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='칼륨'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='salt',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='나트륨'),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='table',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tables.Table', verbose_name='식단'),
        ),
    ]
