# Generated by Django 2.1.7 on 2019-05-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20190527_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['date', 'pk'], 'verbose_name': '식단', 'verbose_name_plural': '식단 목록'},
        ),
    ]
