# Generated by Django 2.2.2 on 2019-06-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20190628_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableattachment',
            name='file',
            field=models.FileField(upload_to='.media/2019-06-28/qSanXx8Z'),
        ),
    ]
