# Generated by Django 2.1.7 on 2019-05-30 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_auto_20190528_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablelog',
            name='date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date(2019, 5, 30), null=True, verbose_name='섭취 일자'),
        ),
    ]
