# Generated by Django 2.1.7 on 2019-05-30 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_auto_20190530_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablelog',
            name='date',
            field=models.DateField(blank=True, db_index=True, default=django.utils.timezone.now, null=True, verbose_name='섭취 일자'),
        ),
    ]
