# Generated by Django 2.2.5 on 2020-01-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_auto_20190628_1040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableAttachment',
        ),
        migrations.AddField(
            model_name='nutrient',
            name='A_iron',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='동물성 철'),
        ),
        migrations.AddField(
            model_name='nutrient',
            name='V_iron',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='식물성 철'),
        ),
        migrations.AddField(
            model_name='table',
            name='ingredients',
            field=models.TextField(blank=True, default=' ', null=True, verbose_name='재료'),
        ),
        migrations.AddField(
            model_name='table',
            name='tips',
            field=models.TextField(blank=True, default=' ', null=True, verbose_name='레시피 팁'),
        ),
        migrations.AlterField(
            model_name='table',
            name='recipe',
            field=models.TextField(blank=True, default=' ', null=True, verbose_name='레시피'),
        ),
        migrations.AlterField(
            model_name='table',
            name='time',
            field=models.CharField(blank=True, choices=[('아침', 'Breakfast'), ('점심', 'Launch'), ('저녁', 'Dinner'), ('간식', 'Snack')], default='아침', max_length=8, null=True, verbose_name='섭취 시간'),
        ),
        migrations.AlterField(
            model_name='tablelog',
            name='time',
            field=models.CharField(blank=True, choices=[('아침', 'Breakfast'), ('점심', 'Launch'), ('저녁', 'Dinner'), ('간식', 'Snack')], default='아침', max_length=8, null=True, verbose_name='섭취 시간'),
        ),
    ]
