"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see

https://docs.djangoproject.com/en/2.1/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
import datetime
import json
import os
import random
import string

from celery.schedules import crontab


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ROOT_DIR = os.path.dirname(BASE_DIR)
TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRETS
SECRETS_DIR = os.path.join(ROOT_DIR, '.secrets')
secrets = json.load(open(os.path.join(SECRETS_DIR, 'base.json')))
SECRET_KEY = secrets['SECRET_KEY']

# Static & Media Settings : DEBUG True 옵션으로 Django 서버에서 정적파일 처리 위한 설정(개발용)

# Static DIR
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/
STATIC_DIR = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [
    STATIC_DIR,
]
STATIC_URL = '/static/'

# collectstatic 사용시의 이동 루트
STATIC_ROOT = os.path.join(ROOT_DIR, '.static')

# Media DIR
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(ROOT_DIR, '.media')


# Auth User Model(Default User Model settings)
AUTH_USER_MODEL = 'members.User'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True > development.py, production.py로 분리


# Application definition

INSTALLED_APPS = [
    'members',
    'tables',
    'information',
    'openpyxl',
    'django.contrib.postgres',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'rest_framework',
    'rest_framework.authtoken',
    'django_elasticsearch_dsl',
    'django_elasticsearch_dsl_drf',
    'rangefilter',
    'django_summernote',
    # 'django_crontab',
]

REST_FRAMEWORK = {
    # DRF Token authentication
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),

    'DEFAULT_RENDERER_CLASSES': (
        'djangorestframework_camel_case.render.CamelCaseJSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'djangorestframework_camel_case.parser.CamelCaseJSONParser',
        # Any other parsers
    ),

    # DRF Throttling
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day'
    }
}

MIDDLEWARE = [
    # Django CORS headers
    # 'corsheaders.middleware.CorsMiddleware',
    # 'django.middleware.common.CommonMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS_ORIGIN_WHITELIST = (
    # Cross Domain을 위한 설정.
    # 프론트엔드(웹)로 부터의 요청을 받는 설정이므로, 현 시점에서는 불필요
    # 해당 프론트엔드 도메인의 주소를 기입하면 된다.
    # ex) cgv.netlify.com
    # '',
# )

# CORS_ALLOW_METHODS = (
#     'DELETE',
#     'GET',
#     'OPTIONS',
#     'PATCH',
#     'POST',
#     'PUT',
# )

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            TEMPLATES_DIR,
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'config.wsgi.application' > production/development.py 분리


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# } > production/development.py 분리


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# CRON TAB > Celery Beat 이관
# Cron Job Settings
# CRONJOBS = [
#     ('0 0 * * *', 'app.cron.table_renewal_job'),
#     ('0 0 1 1 *', 'app.cron.table_log_renewal_job'),
#     ('0 0 1 * *', 'app.cron.user_default_log_job'),
# ]

# settings.py를 분리시켜 운영할 경우, 환경변수 인식을 위해서 필요한 설정.
# CRONTAB_DJANGO_SETTINGS_MODULE = 'app.config.settings.development'

# Celery Settings
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULE = {
    'user-default-log-per-month': {
        'task': 'tables.tasks.make_default_log_monthly',
        'schedule': crontab(day_of_month="1", hour=0, minute=0)
    },
    'table-renewal-per-day': {
        'task': 'tables.tasks.table_renewal',
        'schedule': crontab(hour=0, minute=0)
    },
    'table-log-renewal-per-year': {
        'task': 'tables.tasks.table_log_renewal',
        'schedule': crontab(month_of_year="1", day_of_month="1", hour=0, minute=0)
    },
}

# ElasticSearch_DSL
ELASTICSEARCH_DSL = {
    'default': {
        'hosts': 'localhost:9200'
    }
}


# SummerNote settings
SUMMERNOTE_THEME = 'bs4'


# SUMMERNOTE editor configuration
def random_string():
    rand_string = string.ascii_letters + string.digits
    return ''.join(random.choice(rand_string) for i in range(8))


def summernote_custom_upload_to():
    return ".media/" + datetime.datetime.now().strftime("%Y-%m-%d") + f'/{random_string()}'


SUMMERNOTE_CONFIG = {
    'summernote': {
        'lang': 'ko-KR',
    },
    'attachment_absolute_uri': True,
    'attachment_model': 'tables.TableAttachment',
    'attachment_upload_to': summernote_custom_upload_to(),
}
